from app.models.models import Competitor

competitor_data = {
    "model": Competitor,
    "listOfElements": [
        Competitor(
            id_competitor=15,
            school="EK",
            instructor="BOURSE JAZMIN",
            name="CASTRO NEREA DELFINA",
            age=7,
            belt="AMARILLO",
            isDan=False,
            forms=0,
            jump=0,
            combat=0,
            total=0,
        ),
        Competitor(
            id_competitor=16,
            school="ESC",
            instructor="FLORIANI GABRIEL",
            name="WERNER FERNANDO",
            age=25,
            belt="SEGUNDO DAN",
            isDan=True,
            forms=0,
            jump=0,
            combat=0,
            total=0,
        ),
        Competitor(
            id_competitor=17,
            school="CS",
            instructor="ZAMBELLI NATALIA",
            name="ACEVEDO JULIETA",
            age=8,
            belt="BLANCO PUNTA AMARILLA",
            isDan=False,
            forms=0,
            jump=0,
            combat=0,
            total=0,
        ),
        Competitor(
            id_competitor=18,
            school="ESC",
            instructor="BECERRA GASTON",
            name="ACOSTA BROSSARD MATEO",
            age=12,
            belt="VERDE PUNTA AZUL",
            isDan=False,
            forms=0,
            jump=0,
            combat=0,
            total=0,
        ),
        Competitor(
            id_competitor=19,
            school="EDG",
            instructor="GARCIA DAMIAN",
            name="ACUÑA FABIAN",
            age=11,
            belt="ROJO PUNTA NEGRA",
            isDan=False,
            forms=0,
            jump=0,
            combat=0,
            total=0,
        ),
        Competitor(
            id_competitor=20,
            school="EK",
            instructor="PAEZ GUIDO LEONEL",
            name="ACUÑA SANTIAGO ALEJANDRO",
            age=11,
            belt="VERDE",
            isDan=False,
            forms=0,
            jump=0,
            combat=0,
            total=0,
        ),
        Competitor(
            id_competitor=21,
            school="CS",
            instructor="IRALA JULIAN NAHUEL",
            name="AGUILAR GALEANO ROMEO",
            age=8,
            belt="AMARILLO",
            isDan=False,
            forms=0,
            jump=0,
            combat=0,
            total=0,
        ),
    ],
    "property": "name",
}
