from app.models.models import Competitor

competitor_data = {
    "model": Competitor,
    "listOfElements": [
        Competitor(
            id_competitor=22,
            school="EK",
            instructor="OBREGON HECTOR DAVID",
            name="AGUIRRE LAUTARO GABRIEL",
            age=15,
            belt="AZUL",
            isDan=False,
            forms=0,
            jump=0,
            combat=0,
            total=0,
        ),
        Competitor(
            id_competitor=23,
            school="EK",
            instructor="GADEA BARBARA SOFÍA",
            name="ALBARENGA LISANDRO JORGE",
            age=13,
            belt="VERDE",
            isDan=False,
            forms=0,
            jump=0,
            combat=0,
            total=0,
        ),
        Competitor(
            id_competitor=24,
            school="EK",
            instructor="LUIS GERMÁN MAXIMILIANO",
            name="ALBARRACIN CELESTE MAIA",
            age=7,
            belt="BLANCO",
            isDan=False,
            forms=0,
            jump=0,
            combat=0,
            total=0,
        ),
        Competitor(
            id_competitor=25,
            school="EK",
            instructor="TELLO SANTIAGO",
            name="ALBARRACIN LORENZO",
            age=7,
            belt="BLANCO",
            isDan=False,
            forms=0,
            jump=0,
            combat=0,
            total=0,
        ),
        Competitor(
            id_competitor=26,
            school="EK",
            instructor="TELLO SANTIAGO",
            name="ALBARRACIN MATHEO AGUSTIN",
            age=11,
            belt="BLANCO PUNTA AMARILLA",
            isDan=False,
            forms=0,
            jump=0,
            combat=0,
            total=0,
        ),
        Competitor(
            id_competitor=27,
            school="EK",
            instructor="LUIS GERMÁN MAXIMILIANO",
            name="ALBARRACIN RENZO SANTIAGO",
            age=7,
            belt="BLANCO",
            isDan=False,
            forms=0,
            jump=0,
            combat=0,
            total=0,
        ),
        Competitor(
            id_competitor=28,
            school="EDG",
            instructor="GARCIA DAMIAN",
            name="ALBERTI LISANDRO",
            age=7,
            belt="AMARILLO PUNTA VERDE",
            isDan=False,
            forms=0,
            jump=0,
            combat=0,
            total=0,
        ),
        Competitor(
            id_competitor=29,
            school="EDG",
            instructor="GARCIA DAMIAN",
            name="ALBERTI RENATA",
            age=9,
            belt="AMARILLO PUNTA VERDE",
            isDan=False,
            forms=0,
            jump=0,
            combat=0,
            total=0,
        ),
        Competitor(
            id_competitor=30,
            school="ECT",
            instructor="ACUÑA JAVIER",
            name="ALBINATI JUAN PABLO",
            age=10,
            belt="AZUL PUNTA ROJA",
            isDan=False,
            forms=0,
            jump=0,
            combat=0,
            total=0,
        ),
        Competitor(
            id_competitor=31,
            school="EKH",
            instructor="PRIVITERA JOSE",
            name="ALBINO ZOE CHANTAL",
            age=10,
            belt="AZUL",
            isDan=False,
            forms=0,
            jump=0,
            combat=0,
            total=0,
        ),
        Competitor(
            id_competitor=33,
            school="EK",
            instructor="RADAVERO FRANCO ERNESTO",
            name="ALFONSO MAURO ALEJANDRO",
            age=16,
            belt="ROJO",
            isDan=False,
            forms=0,
            jump=0,
            combat=0,
            total=0,
        ),
        Competitor(
            id_competitor=32,
            school="EK",
            instructor="RADAVERO FRANCO ERNESTO",
            name="ALFONSO AGUSTINA MICAELA",
            age=13,
            belt="AZUL",
            isDan=False,
            forms=0,
            jump=0,
            combat=0,
            total=0,
        ),
        Competitor(
            id_competitor=34,
            school="TN",
            instructor="ACUÑA JAVIER",
            name="ALMEYRA MIA",
            age=7,
            belt="VERDE",
            isDan=False,
            forms=0,
            jump=0,
            combat=0,
            total=0,
        ),
        Competitor(
            id_competitor=35,
            school="ETU",
            instructor="FIORE PABLO",
            name="ALONSO FRANCISCO",
            age=14,
            belt="VERDE PUNTA AZUL",
            isDan=False,
            forms=0,
            jump=0,
            combat=0,
            total=0,
        ),
        Competitor(
            id_competitor=36,
            school="EK",
            instructor="MORILLA WENDY ROCIO",
            name="ALONSO SERGIO",
            age=15,
            belt="BLANCO PUNTA AMARILLA",
            isDan=False,
            forms=0,
            jump=0,
            combat=0,
            total=0,
        ),
        Competitor(
            id_competitor=37,
            school="EKU",
            instructor="PRIOR MARIELA",
            name="ALTOBELLO LISANDRO",
            age=7,
            belt="BLANCO PUNTA AMARILLA",
            isDan=False,
            forms=0,
            jump=0,
            combat=0,
            total=0,
        ),
        Competitor(
            id_competitor=38,
            school="CS",
            instructor="COMPOSTO MARIANO",
            name="ALVARADO NICOLAS",
            age=9,
            belt="BLANCO PUNTA AMARILLA",
            isDan=False,
            forms=0,
            jump=0,
            combat=0,
            total=0,
        ),
        Competitor(
            id_competitor=39,
            school="CS",
            instructor="COMPOSTO MARIANO",
            name="ALVAREZ NICOLAS",
            age=7,
            belt="AMARILLO PUNTA VERDE",
            isDan=False,
            forms=0,
            jump=0,
            combat=0,
            total=0,
        ),
        Competitor(
            id_competitor=12,
            school="EK",
            instructor="TELLO SANTIAGO",
            name="ANDINO GUASCH PABLO ELIAS",
            age=18,
            belt="PRIMER DAN",
            isDan=True,
            forms=0,
            jump=0,
            combat=0,
            total=0,
        ),
        Competitor(
            id_competitor=40,
            school="EK",
            instructor="GADEA BARBARA SOFÍA",
            name="ANDRADE RAMIRO EITAN",
            age=6,
            belt="BLANCO",
            isDan=False,
            forms=0,
            jump=0,
            combat=0,
            total=0,
        ),
        Competitor(
            id_competitor=41,
            school="ETU",
            instructor="FIORE PABLO",
            name="ANTISTA NURIA",
            age=8,
            belt="AMARILLO PUNTA VERDE",
            isDan=False,
            forms=0,
            jump=0,
            combat=0,
            total=0,
        ),
        Competitor(
            id_competitor=42,
            school="ETU",
            instructor="FIORE PABLO",
            name="ANTISTA ROGELIO",
            age=42,
            belt="AZUL PUNTA ROJA",
            isDan=False,
            forms=0,
            jump=0,
            combat=0,
            total=0,
        ),
        Competitor(
            id_competitor=43,
            school="EK",
            instructor="O CONNELL MATEO",
            name="ANTONIO MELGAREJO JONATAN MATIAS",
            age=33,
            belt="AMARILLO PUNTA VERDE",
            isDan=False,
            forms=0,
            jump=0,
            combat=0,
            total=0,
        ),
        Competitor(
            id_competitor=44,
            school="CS",
            instructor="ZAMBELLI NATALIA",
            name="APARICIO AGUSTIN",
            age=13,
            belt="PRIMER DAN",
            isDan=True,
            forms=0,
            jump=0,
            combat=0,
            total=0,
        ),
        Competitor(
            id_competitor=45,
            school="EK",
            instructor="PAEZ GUIDO LEONEL",
            name="APAZA SEBASTIÁN",
            age=13,
            belt="VERDE PUNTA AZUL",
            isDan=False,
            forms=0,
            jump=0,
            combat=0,
            total=0,
        ),
        Competitor(
            id_competitor=46,
            school="EK",
            instructor="PAEZ GUIDO LEONEL",
            name="APAZA THOMÁS IGNACIO",
            age=10,
            belt="VERDE",
            isDan=False,
            forms=0,
            jump=0,
            combat=0,
            total=0,
        ),
        Competitor(
            id_competitor=47,
            school="EK",
            instructor="GADEA BARBARA SOFÍA",
            name="ARDANAZ SGALLA IGNACIO",
            age=21,
            belt="CUARTO DAN",
            isDan=True,
            forms=0,
            jump=0,
            combat=0,
            total=0,
        ),
        Competitor(
            id_competitor=48,
            school="EKU",
            instructor="MINGUILA MARCELO",
            name="ARECO PIA GABRIELA",
            age=17,
            belt="ROJO",
            isDan=False,
            forms=0,
            jump=0,
            combat=0,
            total=0,
        ),
        Competitor(
            id_competitor=49,
            school="CS",
            instructor="COMPOSTO MARIANO",
            name="ARFARÁS TOBIAS",
            age=17,
            belt="SEGUNDO DAN",
            isDan=True,
            forms=0,
            jump=0,
            combat=0,
            total=0,
        ),
    ],
    "property": "name",
}
